/*******************************************
**** Generated by Respack Version 0.0.1 ****
*******************************************/

public class StringPack
{
	public final static int String_1 = 0;
	public final static int STRING_2 = 1;
	public final static int String_3 = 2;
}
