/*******************************************
**** Generated by Respack Version 0.0.1 ****
*******************************************/

public class STRPACK
{
	public final static int MENU_TITLE = 0;
	public final static int DISPLAY_SIZE = 1;
	public final static int VIDEO = 2;
	public final static int AUDIO = 3;
	public final static int EXIT = 4;
}
